Mobile menu implementation
Obote/Profile pull request #9
Opened 2021-08-05 20:39 UTC by Obote

### What does this PR do?

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2021-08-05 22:02 UTC, icebox827 requested changes
Hi Obote, 

Good job so far!
Your project looks good, but there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-05 22:02 UTC, icebox827 commented on index.html
> +            <a class="logo" href="#about">Obote</a>
- [ ] **Required:** It will be nice to have the nav element should be nest inside the header element, not the opposite. Please make the appropriate changes. Use the screenshot below as a guide to better structure your HTML file

![image](https://user-images.githubusercontent.com/2903437/128424454-aabf0306-fcf1-45ba-9be4-866219393804.png)

2021-08-05 22:02 UTC, icebox827 commented on index.js
> +    men.style.display = 'none';
Good job! Your project has followed all the JavaScript requirements, but it needs some improvements.

- [ ] **Required:** Please config linters for JavaScript
- [ ] **Required:** Please have the mobile menu disappeared when a user clicks on the "X" button
- [ ] **Required:** It will be nice to have the mobile menu disappeared when a user clicks on any option in the menu

2021-08-05 22:02 UTC, icebox827 commented on style.css
> +  position: fixed;
Your project looks good, but it requires some improvements.

- [ ] **Required:** It will be nice to change the color of your mobile menu background to this #6070FF according to the Figma template.

2021-08-06 06:40 UTC, hemant-soni-vst-au4 approved these changes
Hello team, 

Good work on implementing the requested changes. 👍 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- We can add the background colour as transparent to the hamburger button. Right now the background is white. Let's fix that to match the original design.
- To make our repo more professional, we can segregate the CSS and js files into different folders.

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-06 06:45 UTC, merged